# Project
version=6.1.1
group=com.mrbysco.particlemimicry

# Common
minecraft_version=1.21.1
neoform_version=1.21.1-20240808.144430
mixin_version=0.16.5+mixin.0.8.7
mixinextras_version=0.5.0

# NeoForge
neo_version=21.1.216
parchment_minecraft_version=1.21.1
parchment_mapping_version=2024.11.17

# Fabric
fabric_version=0.116.7+1.21.1
fabric_loader_version=0.17.2
cloth_config_version=15.0.140
mod_menu_version=11.0.3

mod_name=ChowderExpress
mod_author=Mrbysco
mod_id=chowderexpress

#Publishing
curseforge_id=783410
modrinth_id=CcY0wAVw

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false